#!/bin/sh
mvn clean package && docker build -t jasanishubh123/test .
docker rm -f test 2>/dev/null || true && docker run -it --name test -p 8080:8080 -p 4848:4848 -p 8181:8181 --name test jasanishubh123/test
