#!/bin/sh
mvn clean package && docker build -t jasanishubh123/ShopClientWOJWT .
docker rm -f ShopClientWOJWT 2>/dev/null || true && docker run -it --name ShopClientWOJWT -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ShopClientWOJWT jasanishubh123/ShopClientWOJWT
