#!/bin/sh
mvn clean package && docker build -t jasanishubh123/jakarataMP .
docker rm -f jakarataMP 2>/dev/null || true && docker run -it --name jakarataMP -p 8080:8080 -p 4848:4848 -p 8181:8181 --name jakarataMP jasanishubh123/jakarataMP
