#!/bin/sh
mvn clean package && docker build -t jasanishubh123/ProductResourcesWOJWT .
docker rm -f ProductResourcesWOJWT 2>/dev/null || true && docker run -it --name ProductResourcesWOJWT -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ProductResourcesWOJWT jasanishubh123/ProductResourcesWOJWT
