#!/bin/sh
mvn clean package && docker build -t jasanishubh123/CustomerFront .
docker rm -f CustomerFront 2>/dev/null || true && docker run -it --name CustomerFront -p 8080:8080 -p 4848:4848 -p 8181:8181 --name CustomerFront jasanishubh123/CustomerFront
