#!/bin/sh
mvn clean package && docker build -t jasanishubh123/TestClient .
docker rm -f TestClient 2>/dev/null || true && docker run -it --name TestClient -p 8080:8080 -p 4848:4848 -p 8181:8181 --name TestClient jasanishubh123/TestClient
