#!/bin/sh
mvn clean package && docker build -t jasanishubh123/StockResourcesWOJWT .
docker rm -f StockResourcesWOJWT 2>/dev/null || true && docker run -it --name StockResourcesWOJWT -p 8080:8080 -p 4848:4848 -p 8181:8181 --name StockResourcesWOJWT jasanishubh123/StockResourcesWOJWT
