#!/bin/sh
mvn clean package && docker build -t jasanishubh123/TestResources .
docker rm -f TestResources 2>/dev/null || true && docker run -it --name TestResources -p 8080:8080 -p 4848:4848 -p 8181:8181 --name TestResources jasanishubh123/TestResources
