#!/bin/sh
mvn clean package && docker build -t jasanishubh123/ICTResources .
docker rm -f ICTResources 2>/dev/null || true && docker run -it --name ICTResources -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ICTResources jasanishubh123/ICTResources
