#!/bin/sh
mvn clean package && docker build -t jasanishubh123/ProductClientJWT .
docker rm -f ProductClientJWT 2>/dev/null || true && docker run -it --name ProductClientJWT -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ProductClientJWT jasanishubh123/ProductClientJWT
