#!/bin/sh
mvn clean package && docker build -t jasanishubh123/ProductResources .
docker rm -f ProductResources 2>/dev/null || true && docker run -it --name ProductResources -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ProductResources jasanishubh123/ProductResources
