#!/bin/sh
mvn clean package && docker build -t jasanishubh123/TestJwt .
docker rm -f TestJwt 2>/dev/null || true && docker run -it --name TestJwt -p 8080:8080 -p 4848:4848 -p 8181:8181 --name TestJwt jasanishubh123/TestJwt
